### ISSUE TITLE
Jenkins Telemetry prints warnings on JFR startup

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#193]
```
$ java -jar /c/Users/Oleg/Documents/jenkins/jfr/jenkinsfile-runner/app/target/jenkinsfile-runner-standalone.jar --plugins ../../vanilla-package/target/plugins/ --jenkins-war ../../vanilla-package/target/war/ --runWorkspace work -f .
2019-10-09 14:59:24.300+0000 [id=32]    WARNING hudson.util.PluginServletFilter#addFilter: Filter instance is registered too early: jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter@2a
java.lang.Exception
        at hudson.util.PluginServletFilter.addFilter(PluginServletFilter.java:108)
        at jenkins.telemetry.impl.UserLanguages.setUpFilter(UserLanguages.java:102)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
        at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1095)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-10-09 15:00:14.564+0000 [id=1]     WARNING j.branch.WorkspaceLocatorImpl#getWorkspaceRoot: JENKINS-2111 path sanitization ineffective when using legacy Workspace Root Directory ‘/c/Users/Oleg/Documents/jenkins/jfr/jenkinsfile-runner/demo/declarative-pipeline/work’; switch to ‘${JENKINS_HOME}/workspace/${ITEM_FULL_NAME}’ as in JENKINS-8446 / JENKINS-21942
```

**Comment by oleg-nenashev** [comment]
Follow-up to #184

**Comment by oleg-nenashev** [comment]
As discussed with @daniel-beck , it needs a fix in the Jenkins core so that the `jenkins.telemetry.impl.UserLanguages` does not get initialized so early in the process

**Comment by oleg-nenashev** [comment]
Created https://issues.jenkins-ci.org/browse/JENKINS-60118 for the issue. Will try to fix it, and then I will likely bump Jenkinsfile Runner to the recent weekly

**Comment by oleg-nenashev** [comment]
I plan to release beta-12 with a fix tomorrow.
latest version on DockerHub should be updated in a few hours
