### ISSUE TITLE
How to mock steps using withCredentials types "string", "usernamePassword", etc?

### ISSUE THREAD

**Issue by marcellodesales** [jenkinsci/jenkinsfile-runner#22]
* How can we simulate this locally?
* Is there a way to mock this during running the container?
  * Some sort of volume, creating the expected file loaded by Jenkins?
  * Anything that would make this step run successfully?

```groovy
withCredentials([string(credentialsId: "github.company.com-token", variable: "GITHUB_TOKEN")]) {
          echo "Getting the deploy repo ${paas.gitflow.to.git.repo.replace("github", GITHUB_TOKEN + ":@github")}"
          sh "git clone ${paas.gitflow.to.git.branch} ${paas.gitflow.to.git.repo.replace("github", GITHUB_TOKEN + ":@github")} ${paas.gitflow.to.git.cloneDir}"
          sh "ls -la ${paas.gitflow.to.git.cloneDir}"
        }
```

# Logs

```
$ docker run -v $(pwd):/workspace marcellodesales/jenkinsfile-runner
Started
Running in Durability level: PERFORMANCE_OPTIMIZED
[Pipeline] node
Running on Jenkins in /tmp/jenkinsTests.tmp/jenkins3550020107483346587test/workspace/job
[Pipeline] {
[Pipeline] stage
[Pipeline] }
...
...
...
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
org.jenkinsci.plugins.credentialsbinding.impl.CredentialNotFoundException: Could not find credentials entry with ID 'github.company.com-token'
	at org.jenkinsci.plugins.credentialsbinding.MultiBinding.getCredentials(MultiBinding.java:153)
	at org.jenkinsci.plugins.credentialsbinding.impl.StringBinding.bindSingle(StringBinding.java:62)
	at org.jenkinsci.plugins.credentialsbinding.Binding.bind(Binding.java:150)
	at org.jenkinsci.plugins.credentialsbinding.impl.BindingStep$Execution.start(BindingStep.java:114)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:229)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:153)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62
```

**Comment by ndeloof** [comment]
Seems to me this is a typical use-case for https://github.com/kohsuke/jenkinsfile-runner/issues/15

**Comment by oleg-nenashev** [comment]
In order to mock credentials for local evaluation, you can also consider https://github.com/jenkinsci/JenkinsPipelineUnit or https://github.com/homeaway/jenkins-spock .

Regarding the rest, I also agree with @ndeloof that #15 would be a way to go with this issue. JCasC plugin resolves many such use-cases natively, and you can package everything with [Custom WAR Packager](https://github.com/jenkinsci/custom-war-packager). https://jenkins.io/blog/2018/10/16/custom-war-packager/ and especially https://jenkins.io/blog/2018/10/16/custom-war-packager/#jenkinsfile-runner-packaging
