### ISSUE TITLE
Loading @Library Error: Could not find any definition of libraries [github.com/mozmeao/jenkins-pipeline@master]

### ISSUE THREAD

**Issue by marcellodesales** [jenkinsci/jenkinsfile-runner#23]
Hi there,

I'm trying to run the `Jenkinsfile` from https://github.com/mozilla/kuma/blob/master/Jenkinsfile.

* It loads shared libraries using `@Library`
  * Tried changing to `library`, as suggested at https://jenkins.io/doc/book/pipeline/shared-libraries/#loading-libraries-dynamically

# Questions

* How to run the Build with external libraries expressed with `@Library`?
* How to specify `@Library` with Github Enterprise with Personal-Token only access?
  * I usually get around this using the `TOKEN` as the username with an empty password as https://TOKEN:@github.company.com/mozilla/kuma/blob/master/Jenkinsfile

# Logs with `library`

```groovy
library 'github.com/mozmeao/jenkins-pipeline@master'
```

```
$ docker run -v $(pwd):/workspace marcellodesales/jenkinsfile-runner
Started
Running in Durability level: PERFORMANCE_OPTIMIZED
[Pipeline] library
[Pipeline] End of Pipeline
ERROR: No library named github.com/mozmeao/jenkins-pipeline found
Finished: FAILURE
```

# Logs with `@Library`

```
$ docker run -v $(pwd):/workspace marcellodesales/jenkinsfile-runner
Started
Running in Durability level: PERFORMANCE_OPTIMIZED
ERROR: Could not find any definition of libraries [github.com/mozmeao/jenkins-pipeline@master]
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: Loading libraries failed

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:133)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:559)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:520)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:319)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```

**Comment by marcellodesales** [comment]
@ndeloof have you faced this use-case?

**Comment by ndeloof** [comment]
`jenkinsfile-runner` in it's current design only can run a Jenkinsfile that can execute on a green field jenkins installation without any specific setup. So tons of use cases won't be supported, like using tool installations, credentials, variables, plugins with specific configuration, and ... shared libraries.

For those, we need jenkinsfile-runner to include some jenkins configuration, and I indeed would like to get [JCasC](https://github.com/jenkinsci/configuration-as-code-plugin) used for this purpose.

**Comment by marcellodesales** [comment]
@ndeloof I will check the `JCasC` proposal after I reviewed the Google Doc presentation... The more I try to create reusable Jenkinsfiles, the more I need a better development environment for it. My current development environment is very fragile:

* Shared global libraries are spread-out into multiple Github Repos
* Credentials are usually provided manually in the current Jenkins install 
  * Rotating any secret would require to manually change it through the UI
* I can't use jenkinsfile-runner with libraries, credentials and others as you mentioned

With `JCasC`, it seems like everything would be defined in a `yaml` file and we could bootstrap the Jenkins server locally, by using Docker. I'm still unclear about how we can use the same to bootstrap a Jenkins install in a deployment infrastructure such as Kubernetes, which is our current model. 

I will close this for now.
