### ISSUE TITLE
Error running jenkinsfile-runner on Windows

### ISSUE THREAD

**Issue by ionelanton** [jenkinsci/jenkinsfile-runner#239]
After running 
`jenkinsfile-runner.bat -w C:\Temp\jenkins -p C:\Temp\jenkins_home\plugins -f C:\project`
no plugin in `C:\Temp\jenkins_home\plugins` is loaded.

There is a long list of errors similar to this:

`2019-12-18 21:00:33.499+0000 [id=32]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Trilead API Plugin v1.0.5 (trilead-api)
java.io.IOException: Trilead API Plugin version 1.0.5 failed to load.`
` - You must update Jenkins from version 2.176.2 to version 2.184 or later to run this plugin.
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:868)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:544)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1095)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)`

**Comment by oleg-nenashev** [comment]
"Trilead API Plugin version 1.0.5 failed to load. You must update Jenkins from version 2.176.2 to version 2.184 or later to run this plugin"

**Comment by ionelanton** [comment]
Hi,
I'm using Jenkins ver. 2.190.3

**Comment by woohsi** [comment]
I also meet the same problem

**Comment by oleg-nenashev** [comment]
The next release will bump the minimum required Jenkins core to 2.222.1 (#177). It also includes better Jenkins core version checks, so hopefully this issue will be solved on its won.

**Comment by tavin** [comment]
To confirm oleg-nenashev's comment, I encountered the same issue on linux and resolved it by running the latest snapshot of jenkinsfile-runner with jenkins-2.222.1.

**Comment by oleg-nenashev** [comment]
Fixed by beta-12
