### ISSUE TITLE
-jv (--jenkins-verion) flag crashing CLI

### ISSUE THREAD

**Issue by grinnellian** [jenkinsci/jenkinsfile-runner#257]
Repro'd with example jenkinsfile from Readme. Freshly installed, OSX Catalina; brand new Java & JDK as well. Let me know if I can be of more help tracking this down!

```
% java -jar jenkinsfile-runner-1.0-beta-11.jar -p ./plugins.txt
No explicit version has been selected, using latest LTS
Running pipeline on jenkins 2.204.5
Downloading jenkins 2.204.5...
^C%                                                                                                                     
 % java -jar jenkinsfile-runner-1.0-beta-11.jar -p ./plugins.txt -jv 2.204.5
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1135)
	at hudson.util.VersionNumber.parseVersion(VersionNumber.java:377)
	at hudson.util.VersionNumber.<init>(VersionNumber.java:368)
	at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.isVersionSupported(Bootstrap.java:228)
	at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.postConstruct(Bootstrap.java:144)
	at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.main(Bootstrap.java:121)
% java -jar jenkinsfile-runner-1.0-beta-11.jar -p ./plugins.txt -jv "2.204.5"
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1135)
	at hudson.util.VersionNumber.parseVersion(VersionNumber.java:377)
	at hudson.util.VersionNumber.<init>(VersionNumber.java:368)
	at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.isVersionSupported(Bootstrap.java:228)
	at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.postConstruct(Bootstrap.java:144)
	at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.main(Bootstrap.java:121)
```

**Comment by oleg-nenashev** [comment]
I would guess that VersionNumber parser received a Null input in https://github.com/jenkinsci/jenkinsfile-runner/blob/master/bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java#L234 . Theire is either a miracle or `readPropertyFromPom("jenkins.version")` not working as expected
