### ISSUE TITLE
[JENKINS-56268] - NullPointerException when specifying -f Jenkinsfile without a path

### ISSUE THREAD

**Issue by lhupfeldt** [jenkinsci/jenkinsfile-runner#28]
Running
```
jenkinsfile-runner ... -f Jenkinsfile
```
results in:
```
java.lang.NullPointerException
	at hudson.FilePath.<init>(FilePath.java:272)
	at io.jenkins.jenkinsfile.runner.FileSystemSCM.checkout(FileSystemSCM.java:37)
	...
```
Running
```
jenkinsfile-runner ... -f ./Jenkinsfile
```
works

**Comment by oleg-nenashev** [comment]
Moved to https://issues.jenkins-ci.org/browse/JENKINS-56268
