### ISSUE TITLE
NoClassDefFoundError: com/trilead/ssh2/crypto/cipher/BlockCipher

### ISSUE THREAD

**Issue by jeremyweber-np** [jenkinsci/jenkinsfile-runner#307]
Ive tried for a few days to narrow this down, but havent had any luck!  Using the current master branch slightly modified to use  jenkins 2.231 in the docker image.

Simple Jenkinsfile:
```
node {
  echo "What the..."
  checkout([
      $class: 'GitSCM',
      branches: [[name: 'dev']],
      doGenerateSubmoduleConfigurations: false,
      extensions: [
          [$class: 'RelativeTargetDirectory', relativeTargetDir: '.']
      ],
      userRemoteConfigs: [
        [
          credentialsId: 'some_cred_id,
          name: 'origin',
          refspec: '+refs/heads/*:refs/remotes/origin/*',
          url: 'git@github.xxx/app'
        ]
      ]
    ])
}
```
Result:
```
Started
Running in Durability level: PERFORMANCE_OPTIMIZED
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /build
[Pipeline] {
[Pipeline] echo
What the...
[Pipeline] checkout
using credential some_cred_id
Cloning the remote Git repository
Cloning repository git@github.com:xxx/app
 > git init /build # timeout=10
Fetching upstream changes from  git@github.com:xxx/app
 > git --version # timeout=10
using GIT_SSH to set credentials Jenkins SSH Key
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.lang.ClassNotFoundException: com.trilead.ssh2.crypto.cipher.BlockCipher
        at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1387)
        at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
        at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1089)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
Caused: java.lang.NoClassDefFoundError: com/trilead/ssh2/crypto/cipher/BlockCipher
        at com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey.getPrivateKeys(BasicSSHUserPrivateKey.java:174)
        at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.createSshKeyFile(CliGitAPIImpl.java:2060)
        at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1970)
        at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:81)
        at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:569)
        at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:798)
        at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1114)
        at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1159)
        at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
        at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
        at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
        at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

So I have confirmed the docker jenkins-runner image contains the trilead plugin and that it does have the classes referenced.  Ive tried with a minimal set of plugins and with the whole list of plugins from out production instance.  There are also similar and other stack traces that occur before the build, I included them in the log file below:

[test.log](https://github.com/jenkinsci/jenkinsfile-runner/files/4772691/test.log)

Not sure if I am missing something simple, complex or what... Any guidance would be appreciated.

**Comment by jeremyweber-np** [comment]
Im going to close this, as i have worked around the issue by crafting my own docker image based on a jenkins base with the jenkinsfile-runner included.
