### ISSUE TITLE
Configured tools like Maven cannot be resolved

### ISSUE THREAD

**Issue by gortazar** [jenkinsci/jenkinsfile-runner#309]
When running pipelines that reference tools installed in the referenced exploded jenkins war folder, these tools are not recognized by jenkinsfile-runner, and hence the build fails.

The following pipeline references a maven M3 tool:

```
node {
   def mvnHome
   stage('Preparation') { // for display purposes
      git 'https://github.com/jglick/simple-maven-project-with-tests.git'
      mvnHome = tool 'M3'
   }
   stage('Build') {
         sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
      } else {
         bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
      }
   }
   stage('Results') {
      junit '**/target/surefire-reports/TEST-*.xml'
      archive 'target/*.jar'
   }
}
```

When run with:

    ~/jenkins-war/jenkinsfile-runner-1.0-beta-12/bin/jenkinsfile-runner -w ~/.jenkins -p ~/.jenkins/plugins -f Jenkinsfile2 -ns

where ~/.jenkins is an exploded jenkins war folder that includes a configuration for a maven tool named M3, the following error is raised:

```
Running in Durability level: PERFORMANCE_OPTIMIZED
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /tmp/jenkinsfileRunner.tmp/jfr5698454769998809354.run/workspace/job
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Preparation)
[Pipeline] git
No credentials specified
Cloning the remote Git repository
Cloning repository https://github.com/jglick/simple-maven-project-with-tests.git
 > git init /tmp/jenkinsfileRunner.tmp/jfr5698454769998809354.run/workspace/job # timeout=10
Fetching upstream changes from https://github.com/jglick/simple-maven-project-with-tests.git
 > git --version # timeout=10
 > git fetch --tags --progress -- https://github.com/jglick/simple-maven-project-with-tests.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/jglick/simple-maven-project-with-tests.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/jglick/simple-maven-project-with-tests.git # timeout=10
Fetching upstream changes from https://github.com/jglick/simple-maven-project-with-tests.git
 > git fetch --tags --progress -- https://github.com/jglick/simple-maven-project-with-tests.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision b3a39b21ac048d9298986e0d4a1d9f4dd185df8f (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f b3a39b21ac048d9298986e0d4a1d9f4dd185df8f # timeout=10
 > git branch -a -v --no-abbrev # timeout=10
 > git checkout -b master b3a39b21ac048d9298986e0d4a1d9f4dd185df8f # timeout=10
Commit message: "Merge pull request #13 from jglick/Jenkinsfile"
First time build. Skipping changelog.
[Pipeline] tool
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: No tool named M3 found
Finished: FAILURE
```

Is it any way jenkinsfile-runner can honour configuration of tools and any other plugin in the referenced jenkins war folder?

**Comment by gortazar** [comment]
When run against a declarative maven (with a `tool M3` tool declaration) the error message is a bit more informative:

```
Started
Running in Durability level: PERFORMANCE_OPTIMIZED
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 5: Tool type "maven" does not have an install of "M3" configured - did you mean "null"? @ line 5, column 11.
       maven "M3"
             ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:561)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:522)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:337)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Finished: FAILURE
```

**Comment by oleg-nenashev** [comment]
Hi. Sorry, I missed the notification. It is not enough to install a tool in the image. If you use a `M3` tool declaration, such tool should be configured in the Jenkins configuration.

Example for Gtoovy scripts: https://github.com/jenkinsci/ci.jenkins.io-runner/blob/master/init_scripts/src/main/groovy/Tools.groovy

Example for JCasC: https://github.com/oleg-nenashev/demo-jenkins-config-as-code/blob/master/jenkins.yaml#L110-L114

**Comment by oleg-nenashev** [comment]
Please reopen if the answer above does not resolve the issue
