### ISSUE TITLE
ConfiguratorException when using casc credentials with 1.0-beta-13/14

### ISSUE THREAD

**Issue by bparzella** [jenkinsci/jenkinsfile-runner#345]
When starting jenkinsfile-runner with credentials present in the casc yaml, an exception occurs during launch:

```
2020-07-28 11:42:58.176+0000 [id=28]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed ConfigurationAsCode.init
io.jenkins.plugins.casc.ConfiguratorException: No configurator for the following root elements credentials
        at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:713)
        at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:755)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:740)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:616)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:298)
        at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:290)
Caused: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
        at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

The configuration yaml:
```
credentials:
  system:
    domainCredentials:
      - credentials:
          - UsernamePasswordCredentialsImpl:
              scope: GLOBAL
              id: sample_credential
              username: sample_user
              password: sample_password
```

This constellation still worked with beta-12.

Am I missing some config change or required plugin?

[plugins.txt](https://github.com/jenkinsci/jenkinsfile-runner/files/4988061/plugins.txt)

**Comment by oleg-nenashev** [comment]
@bparzella your `plugins.txt` is missing versions, so it is hard to say for sure which ones are actually installed. Do you use the `--plugins` parameter? And which Jenkins core version do you use?

On the investigation side, the `credentials` category configurator relies on some class locations in https://github.com/jenkinsci/configuration-as-code-plugin/blob/02ca4728571a26465339742f532c9e50fe629b07/plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/GlobalConfigurationCategoryConfigurator.java#L124-L132 . If the `com.cloudbees.plugins.credentials.CredentialsProviderManager$Configuration` class is moved, it will lead to the reported behavior. At the same time the class is still there: https://github.com/jenkinsci/credentials-plugin/blob/master/src/main/java/com/cloudbees/plugins/credentials/CredentialsProviderManager.java#L338-L345 . CC @timja @jetersen just in case I am missing something

**Comment by timja** [comment]
Need more logs, probably the credentials plugin failed to load for some reason

**Comment by bparzella** [comment]
I use this plugins.txt with the -p parameter, so all the plugins are latest. The core is also the one jenkins-runner downloads (_No explicit version has been selected, using latest LTS. Running pipeline on jenkins 2.235.3_). The operating system is Windows.

I attached a logfile, but I don't know if it provides the information needed. If not, I need a hint on how to create a useful log file.

[jenkins-runner.log](https://github.com/jenkinsci/jenkinsfile-runner/files/4988892/jenkins-runner.log)

**Comment by oleg-nenashev** [comment]
Uhm:

```
2020-07-28 14:10:12.659+0000 [id=38]	FINER	hudson.ExtensionList#load: Loading ExtensionList 'hudson.ExtensionFinder' from
java.lang.Throwable: Only present for stacktrace information
	at hudson.ExtensionList.load(ExtensionList.java:378)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:317)
	at hudson.ExtensionList.getComponents(ExtensionList.java:183)
	at jenkins.model.Jenkins$6.onInitMilestoneAttained(Jenkins.java:1161)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:85)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.lambda$onAttained$3(ReactorListener.java:102)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.run(ReactorListener.java:109)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:102)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:177)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-07-28 14:10:13.634+0000 [id=38]	FINE	hudson.ExtensionFinder$Sezpoz#scout: Failed to scout com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator
java.lang.ClassNotFoundException: io.jenkins.plugins.casc.RootElementConfigurator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
Caused: java.lang.NoClassDefFoundError: io/jenkins/plugins/casc/RootElementConfigurator
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.java.sezpoz.IndexItem.element(IndexItem.java:134)
Caused: java.lang.InstantiationException
	at net.java.sezpoz.IndexItem.element(IndexItem.java:146)
	at hudson.ExtensionFinder.getClassFromIndex(ExtensionFinder.java:746)
	at hudson.ExtensionFinder.access$900(ExtensionFinder.java:90)
	at hudson.ExtensionFinder$Sezpoz.scout(ExtensionFinder.java:731)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:340)
	at hudson.ExtensionList.load(ExtensionList.java:381)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:317)
	at hudson.ExtensionList.getComponents(ExtensionList.java:183)
	at jenkins.model.Jenkins$6.onInitMilestoneAttained(Jenkins.java:1161)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:85)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.lambda$onAttained$3(ReactorListener.java:102)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.run(ReactorListener.java:109)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:102)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:177)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bparzella** [comment]
This extensive log output is only displayed when I try to start with log output for level FINER, with normal logging only the message from my first post is printed.

Am I missing something?

**Comment by oleg-nenashev** [comment]
It would be possible to use even higher logging level to capture the plugin loading sequence. The issue is actually with the JCasC classloading, but I am not sure what happened. It might be related to different classloaders

@bparzella I will try to reproduce it locally with published binaries

**Comment by oleg-nenashev** [comment]
UPD: I was unable to reproduce it. I suspect plugin version conflicts. JCasC is currently included by default into JFR, and hence it will use the JCasC version from the bundle. I consider detaching JCasC and using it only inside Vanilla

**Comment by oleg-nenashev** [comment]
@bparzella are you still interested in the issue? As I said above, I was not able to reproduce it

**Comment by bparzella** [comment]
I tried both, the latest version and removed the CasC from the plugin list but nothing changed.

What else can I do to find the source of this problem? Could it be the java version? Could it be related to windows?

As I am on holiday at the moment, I can run further tests from the beginning of september.

**Comment by oleg-nenashev** [comment]
I am running JFR on Windows as well, so unlikely. It might be just related to the JFR version quirks.

**Comment by bparzella** [comment]
So I did some more testing and I created a minimal example that reproduces the error for me.

Background: in my use case the pipeline uses credentials, which are defined in the casc yaml.

So if I have the casc plugin present in the plugins.txt (which was okay before beta 13), I get the error I reported initially. This is how the attached example is set up. 

If I remove the casc plugin from the plugins.txt, there seems to be an issue, loading the credentials from the casc yaml:
```
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in d:\UserData\z0046afz\src\jfr_test\workspace
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: sample_credential
Finished: FAILURE
```

(This error is the same in beta 12.)

To reproduce this error with the example, simply remove casc from the plugins.txt.

The Example:
A script for downloading the JFR jar is present in the install folder, the jfr_test.bat runs JFR with plugins, config and Jenkinsfile.

[jfr_test.zip](https://github.com/jenkinsci/jenkinsfile-runner/files/5174969/jfr_test.zip)

**Comment by bparzella** [comment]
Are there any news on this one? Are there any clarifications required?

**Comment by oleg-nenashev** [comment]
Sorry, I missed the previous message due to my vacation @bparzella . I will try to take a look

**Comment by brice-pinguetti** [comment]
I face the exact same issue.

As an additional info, I can mention that I don't use the Vanilla image, but beta-17 version of the jenkinsfile-runner jar file.
Then for the plugins folder, I copied it from a Jenkins master docker container built from scratch on my local machine, in which I installed all the plugins, including JCasC from the UI.

**Comment by bparzella** [comment]
I just tried beta19 and it seems to be working.

Any updates? If not I'll close the issue.
