### ISSUE TITLE
Create project NPE

### ISSUE THREAD

**Issue by stickycode** [jenkinsci/jenkinsfile-runner#377]
version 1.0-beta-17 (and -16 and -15)
jenkins version 2.255 and 2.257

I'm getting this NPE running java -jar target/jenkins/jenkinsfile-runner-1.0-beta-17.jar -p target/jenkins/plugins -w target/jenkins/war

doesn't seem to matter the java version or the jenkins version or the runner version

if this something to do with plugin initialization?

2020-10-01 22:13:20.367+0000 [id=1]     SEVERE  h.i.i.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler#uncaughtException: A thread (main/1) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.NullPointerException
        at hudson.model.ItemGroupMixIn.createProject(ItemGroupMixIn.java:311)
        at jenkins.model.Jenkins.createProject(Jenkins.java:3002)
        at jenkins.model.Jenkins.createProject(Jenkins.java:2998)
        at jenkins.model.Jenkins.createProject(Jenkins.java:3033)
        at io.jenkins.jenkinsfile.runner.Runner.run(Runner.java:46)
Caused: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at io.jenkins.jenkinsfile.runner.JenkinsfileRunnerLauncher.doLaunch(JenkinsfileRunnerLauncher.java:32)
        at io.jenkins.jenkinsfile.runner.JenkinsLauncher.launch(JenkinsLauncher.java:77)
        at io.jenkins.jenkinsfile.runner.App.run(App.java:13)
        at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.run(Bootstrap.java:307)
        at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.main(Bootstrap.java:128)

**Comment by oleg-nenashev** [comment]
So t happens, because the project Descriptor for `WorkflowJob` cannot be found:

```
 public synchronized TopLevelItem createProject( TopLevelItemDescriptor type, String name, boolean notify )
            throws IOException {
        acl.checkPermission(Item.CREATE);
311>>>        type.checkApplicableIn(parent);
        acl.getACL().checkCreatePermission(parent, type);

```

Most likely it happens because of the Pipeline: Job plugin boot failure. @stickycode could you please provide a full startup log? It would be also nice to know versions of plugins you use.

**Comment by stickycode** [comment]
By default thats all the logs just a stack trace. 

Ill get the plugin list and see about more logs .

**Comment by oleg-nenashev** [comment]
@stickycode Hi. Did you have a chance to collect the diagnostics info?

**Comment by stickycode** [comment]
Not yet been on holiday

**Comment by stickycode** [comment]
I was on holiday, I hope to get back to it next week

**Comment by oleg-nenashev** [comment]
Please feel free to reopen the issue once you could provide the startup log, thanks!
