### ISSUE TITLE
Root URL isn't configured yet. Cannot compute absolute URL.

### ISSUE THREAD

**Issue by henryborchers** [jenkinsci/jenkinsfile-runner#421]
I don't know if this is an issue with the Jenkisfile-runner, Jenkins CasC, or the Warnings Next Generation plugin but I do know that I only have this issue when I'm running a jenkinsfile in the Jenkinsfile-runner. 

If I have any pipeline that uses the Warnings Next Generation's recordIssues command without explicitly adding skipPublishingChecks: true, I get the following error and the build fails.

java.lang.IllegalStateException: Root URL isn't configured yet. Cannot compute absolute URL.

**Comment by oleg-nenashev** [comment]
@henryborchers Hi. I confirm that it might be a behavior with Jenkinsfile Runner if you do not explicitly define local URL in the configuration YAML.

The issue seems to be coming from the Ownership plugin: https://github.com/jenkinsci/ownership-plugin/blob/2b619c3a7dfaa4b706b19560dc465040b1de2dc4/src/main/java/com/synopsys/arc/jenkins/plugins/ownership/nodes/NodeOwnershipAction.java . Would it be possible to provide a full error stacktrace so that I could confirm that?

**Comment by timja** [comment]
It's the displayurl api plugin I believe

**Comment by henryborchers** [comment]
> Would it be possible to provide a full error stacktrace so that I could confirm that?

Here you go.
```
java.lang.IllegalStateException: Root URL isn't configured yet. Cannot compute absolute URL.
	at hudson.model.Item.getAbsoluteUrl(Item.java:205)
	at hudson.model.AbstractItem.getAbsoluteUrl(AbstractItem.java:587)
	at hudson.model.Run.getAbsoluteUrl(Run.java:1060)
	at io.jenkins.plugins.analysis.core.model.ResultAction.getAbsoluteUrl(ResultAction.java:187)
	at io.jenkins.plugins.analysis.core.steps.WarningChecksPublisher.extractChecksDetails(WarningChecksPublisher.java:75)
	at io.jenkins.plugins.analysis.core.steps.WarningChecksPublisher.publishChecks(WarningChecksPublisher.java:55)
	at io.jenkins.plugins.analysis.core.steps.IssuesRecorder.publishResult(IssuesRecorder.java:725)
	at io.jenkins.plugins.analysis.core.steps.IssuesRecorder.record(IssuesRecorder.java:651)
	at io.jenkins.plugins.analysis.core.steps.IssuesRecorder.perform(IssuesRecorder.java:617)
	at io.jenkins.plugins.analysis.core.steps.RecordIssuesStep$Execution.run(RecordIssuesStep.java:1024)
	at io.jenkins.plugins.analysis.core.steps.RecordIssuesStep$Execution.run(RecordIssuesStep.java:985)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by oleg-nenashev** [comment]
So, it happens because Jenkinsfile Runner, similarly to Jenkins, does not initialize the default URL on startup. In classic Jenkins Setup Wizard offers to do it, but this is optional. I am not sure what to do in this case by default. Jenkinsfile Runner has no URL since it has no web interface. https://github.com/jenkinsci/display-url-api-plugin can help with that, but only on instances which offer alternate UI. 

We have two options:

1. *Hard Mode:* Declare "undefined" Root UL a normal behavior for headless Jenkins instances. Fix the plugins not supporting it (CC @uhafner since Analysis Core is reported)
2. *Hack Mode*: Initialize Jenkinsfile Runner with a mock URL like "http://undefined". The logic in plugin will work, but it will produce meaningless results

## Workarounds

In JCasC:

```yaml
jenkins:
      location:
        url: http://jenkins/
```

In code:

```
JenkinsLocationConfiguration.get().setUrl(JENKINS_URL)
```

**Comment by timja** [comment]
I would just define a url, github requires a url to point to when you send it things like commit statuses and checks, some APIs are handling it by putting in rubbish, but why not just configure something?

**Comment by henryborchers** [comment]
@oleg-nenashev I honestly don't care what the result of the recordissues. I just want to make sure that I test my pipeline locally so I don't have to commit my changes into SCM and wait for the main server to point out my flaws.
I'm happy with adding a mock url. 
> Workarounds
> In JCasC:
> 
> ```
> jenkins:
>       location:
>         url: http://jenkins/
> ```

"location" doesn't seem to exist in the jenkins key

It does seem to exist in unclassified key, however, it doesn't seem to have an effect.

**Comment by uhafner** [comment]
I fixed that part already in HEAD of the warnings plugin. It will be part of the next release.

**Comment by henryborchers** [comment]
@uhafner Any idea when you're going to release the next version?

**Comment by uhafner** [comment]
Before or shortly after Christmas. It is almost ready but since this release contains some major changes I need to have some spare time reserved after the release to be prepared for occasional bug fixes.

**Comment by henryborchers** [comment]
@uhafner That's fair. I didn't mean to be pushy. I'm just very excited about not having to see "java.lang.IllegalStateException: Root URL isn't configured yet. Cannot compute absolute URL."

**Comment by henryborchers** [comment]
@uhafner and @oleg-nenashev this was resolved with the recent version of warnings-ng plugin. it works beautifully

**Comment by oleg-nenashev** [comment]
FTR https://github.com/jenkinsci/warnings-ng-plugin/commit/18f7c799f8085a48471405f66672d3982de81feb in 8.5.0
