### ISSUE TITLE
hudson.util.PluginServletFilter.addFilter Filter instance is registered too early

### ISSUE THREAD

**Issue by wangjia2016** [jenkinsci/jenkinsfile-runner#422]
jenkins version：2.249.3
centos ：CentOS Linux release 7.2.1511
tomcat version ：8.5.59
java：javac 1.8.0_271

`19-Nov-2020 17:11:29.743 WARNING [UserLanguages.setUpFilter] hudson.util.PluginServletFilter.addFilter Filter instance is registered too early: jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter@2a
	java.lang.Exception
		at hudson.util.PluginServletFilter.addFilter(PluginServletFilter.java:108)
		at jenkins.telemetry.impl.UserLanguages.setUpFilter(UserLanguages.java:103)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
		at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
		at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
		at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
		at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
		at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
		at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
19-Nov-2020 17:11:29.743 WARNING [ResourceDomainFilter.init] hudson.util.PluginServletFilter.addFilter Filter instance is registered too early: jenkins.security.ResourceDomainFilter@1e0b0797
	java.lang.Exception
		at hudson.util.PluginServletFilter.addFilter(PluginServletFilter.java:108)
		at jenkins.security.ResourceDomainFilter.init(ResourceDomainFilter.java:57)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
		at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
		at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
		at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
		at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
		at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
		at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
19-Nov-2020 17:11:29.777 INFO [pool-6-thread-5] jenkins.InitReactorRunner$1.onAttained System config loaded`

on startup throws exception 

`19-Nov-2020 17:17:17.997 INFO [Thread-5] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8100"]
19-Nov-2020 17:17:18.003 INFO [Thread-5] org.apache.catalina.core.StandardService.stopInternal Stopping service [Catalina]
19-Nov-2020 17:17:18.013 INFO [localhost-startStop-2] jenkins.model.Jenkins.cleanUp Stopping Jenkins
19-Nov-2020 17:17:18.060 INFO [localhost-startStop-2] jenkins.model.Jenkins$18.onAttained Started termination
19-Nov-2020 17:17:18.071 INFO [localhost-startStop-2] jenkins.model.Jenkins$18.onAttained Completed termination
19-Nov-2020 17:17:18.071 INFO [localhost-startStop-2] jenkins.model.Jenkins._cleanUpDisconnectComputers Starting node disconnection
19-Nov-2020 17:17:18.074 INFO [localhost-startStop-2] jenkins.model.Jenkins._cleanUpShutdownPluginManager Stopping plugin manager
19-Nov-2020 17:17:18.076 WARNING [Executor #1 for master : executing platform-wechat #54] jenkins.model.PeepholePermalink.updateCache failed to update /home/www/.jenkins/jobs/platform/builds/permalinks
	java.nio.channels.ClosedByInterruptException`

and then the tomcat is down the process is being killed

**Comment by oleg-nenashev** [comment]
@wangjia2016 Which Jenkinsfile Runner version do you use? AFAICT this issue was fixed in beta-12: https://github.com/jenkinsci/jenkinsfile-runner/issues/193

**Comment by oleg-nenashev** [comment]
@wangjia2016 gentle ping

**Comment by oleg-nenashev** [comment]
closing due to no response
