### ISSUE TITLE
JFR Container Builder - Build Issue

### ISSUE THREAD

**Issue by satrox28** [jenkinsci/jenkinsfile-runner#452]
We are trying to evaluate Jenkins to Gitlab migration and noticed jenkinsfile runner can be used. We are encountering the below error when trying to perform Jenkinsfile Runner Container Builder, can you please check and advice.

Jenkins Version: 2.235.5
~~~
#[root@ jfr-container-builder]# bin/jfr-container-builder init --jfr-version 1.0-beta-25  --jenkins-home /mnt/jenkins2 --jenkins-plugins /mnt/jenkins2/plugins --jenkins-war jenkins.war --agent-type shell --build-output /root/jfr-container-builder
Running init with --jfr-version=1.0-beta-25 --jenkins-home=/mnt/jenkins2 --jenkins-war=jenkins.war --jenkins-plugins=/mnt/jenkins2/plugins --agent-type=shell --build-output=/root/jfr-container-builder
/usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1276:in `copy': cannot handle socket (RuntimeError)
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:416:in `block in copy_entry'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1388:in `wrap_traverse'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1391:in `block in wrap_traverse'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1390:in `each'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1390:in `wrap_traverse'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1391:in `block in wrap_traverse'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1390:in `each'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1390:in `wrap_traverse'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1391:in `block in wrap_traverse'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1390:in `each'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1390:in `wrap_traverse'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1391:in `block in wrap_traverse'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1390:in `each'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1390:in `wrap_traverse'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:413:in `copy_entry'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:391:in `block in cp_r'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1461:in `block in fu_each_src_dest'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1477:in `fu_each_src_dest0'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:1459:in `fu_each_src_dest'
        from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:390:in `cp_r'
        from /root/jfr-container-builder/lib/jenkinsfile_runner/commands/init.rb:55:in `copy_jenkins_home_directory'
        from /root/jfr-container-builder/lib/jenkinsfile_runner/commands/init.rb:22:in `run'
        from /root/jfr-container-builder/lib/jenkinsfile_runner/cli.rb:12:in `run'
        from bin/jfr-container-builder:9:in `<main>'
~~~
~~~ 
# docker version
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:13:48 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:12:26 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
~~~
~~~
#ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
~~~

**Comment by oleg-nenashev** [comment]
Hello. Please report it to https://gitlab.com/gitlab-org/jfr-container-builder
