### ISSUE TITLE
jenkinsfileRunner very slow

### ISSUE THREAD

**Issue by Katsu1991** [jenkinsci/jenkinsfile-runner#471]
when i run "app/target/appassembler/bin/jenkinsfile-runner -w ../jenkins.war -p ~/.jenkins/plugins  -f Jenkinsfile", it spend 4 minutes，Jenkinsfile content as follows：
"
pipeline {
    agent any
    stages {
        stage('test') {
            steps {
                echo "Begin bash..."
		sh '''
		a=10
		b=20
		c=`expr $a + $b`
		echo "c is : $c"
		'''
	    }
        }
    }
}
"

**Comment by Katsu1991** [comment]
i guess that is jenkinsfileRunner  startup slowly ,it is the problem of jenkinsfileRunner-self

i am anxious ，online wait

**Comment by oleg-nenashev** [comment]
Could you please provide the startup log? Please use a custom log file to enable detailed logging: https://github.com/jenkinsci/jenkinsfile-runner/blob/master/docs/using/TROUBLESHOOTING.adoc#logging

**Comment by michaelneale** [comment]
interested to know where slowness is happening here.

**Comment by michaelneale** [comment]
also - what plugins are you adding?

**Comment by Katsu1991** [comment]
> Could you please provide the startup log? Please use a custom log file to enable detailed logging: https://github.com/jenkinsci/jenkinsfile-runner/blob/master/docs/using/TROUBLESHOOTING.adoc#logging

**Comment by Katsu1991** [comment]
1.exec command:
java -Djava.util.logging.config.file=logging.properties -jar -Xmx4g -Xms4g /Users/zhuxiaoge/dev/projects/jenkinsfile-runner/app/target/jenkinsfile-runner-standalone.jar -w ../jenkins.war -p /Users/zhuxiaoge/.jenkins/plugins  -f Jenkinsfile

2.console log:
Exploding,/Users/zhuxiaoge/dev/jenkins/jenkinsfile-runner/../jenkins.warthis might take some time.
Bad level value for property: .level
Bad level value for property: java.util.logging.ConsoleHandler.level
java.lang.RuntimeException: Unhandled exception
	at io.jenkins.jenkinsfile.runner.bootstrap.commands.JenkinsLauncherCommand.call(JenkinsLauncherCommand.java:59)
	at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.call(Bootstrap.java:70)
	at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.call(Bootstrap.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.main(Bootstrap.java:45)
Caused by: java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at io.jenkins.jenkinsfile.runner.bootstrap.commands.JenkinsLauncherCommand.getAppRepo(JenkinsLauncherCommand.java:241)
	at io.jenkins.jenkinsfile.runner.bootstrap.commands.JenkinsLauncherCommand.lambda$createJenkinsWarClassLoader$0(JenkinsLauncherCommand.java:169)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.jenkins.jenkinsfile.runner.bootstrap.commands.JenkinsLauncherCommand.createJenkinsWarClassLoader(JenkinsLauncherCommand.java:164)
	at io.jenkins.jenkinsfile.runner.bootstrap.commands.JenkinsLauncherCommand.runJenkinsfileRunnerApp(JenkinsLauncherCommand.java:191)
	at io.jenkins.jenkinsfile.runner.bootstrap.commands.JenkinsLauncherCommand.call(JenkinsLauncherCommand.java:57)
	... 10 more

3.parameter description:
    1)logging.properties: from jdk8, i update level from INFO to DEBUG
    2)jenkinsfile-runner-standalone.jar: package from jenkinsfile-ruuner github repo, master branch
    3)jenkins.war: download from jenkins official
    4)plugins: my local jenkins plugins , there are about 103 plugins
    5)Jenkinsfile: please see above

That's all.
 It's strange，when  use app/target/appassembler/bin/jenkinsfile-runner, it work although slow; but use app/target/jenkinsfile-runner-standalone.jar, it doesn't work and slowly too.

**Comment by Katsu1991** [comment]
Because I didn't unzip the jenkins.war package
