### ISSUE TITLE
Unable to run jenkinsfile-runner; java classes not found

### ISSUE THREAD

**Issue by marounayli** [jenkinsci/jenkinsfile-runner#497]
I have been attempting to use the Jenkins runner script along a jenkins war file.

jenkinsfile-runner -w <path-to-war> .

I did the following:

wget http://mirrors.jenkins.io/war-stable/latest/jenkins.war
unzip jenkins.war -d /tmp/jenkins

JENKINS_HOME=/tmp/jenkins_home java -jar jenkins.war

I did this to install the plugins in jenkins_home to be referenced later

I ran this war file and installed all the default plugins.

I then turned it off and ran the following:

./jenkinsfile-runner -w /tmp/jenkins -p /tmp/jenkins_home/plugins -f <jenkinsfile_location>

I am getting the following error: java.lang.ClassNotFoundException: org.jenkinsci.plugins.workflow.multibranch.yaml.pipeline.PipelineAsYamlScriptFlowDefinition

For reference I used the following tutorial : https://reposhub.com/java/build/jenkinsci-jenkinsfile-runner.html

**Comment by oleg-nenashev** [comment]
Could you please provide the full stacktrace?
Also, which Jenkinsfile Runner version are you using?

**Comment by marounayli** [comment]
jenkinsfile-runner version : 1.0-beta-25

Stack Trace
 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/tmp/jenkins/WEB-INF/lib/guice-4.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.RuntimeException: Unhandled exception
        at io.jenkins.jenkinsfile.runner.bootstrap.commands.JenkinsLauncherCommand.call(JenkinsLauncherCommand.java:59)
        at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.call(Bootstrap.java:70)
        at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.call(Bootstrap.java:21)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.main(Bootstrap.java:45)
Caused by: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/multibranch/yaml/pipeline/PipelineAsYamlScriptFlowDefinition
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
        at java.base/java.lang.Class.getMethodsRecursive(Class.java:3307)
        at java.base/java.lang.Class.getMethod0(Class.java:3293)
        at java.base/java.lang.Class.getMethod(Class.java:2106)
        at io.jenkins.jenkinsfile.runner.JenkinsfileRunnerLauncher.doLaunch(JenkinsfileRunnerLauncher.java:36)
        at io.jenkins.jenkinsfile.runner.JenkinsLauncher.launch(JenkinsLauncher.java:103)
        at io.jenkins.jenkinsfile.runner.App.run(App.java:21)
        at io.jenkins.jenkinsfile.runner.bootstrap.commands.JenkinsLauncherCommand.runJenkinsfileRunnerApp(JenkinsLauncherCommand.java:198)
        at io.jenkins.jenkinsfile.runner.bootstrap.commands.JenkinsLauncherCommand.call(JenkinsLauncherCommand.java:57)
        ... 10 more
Caused by: java.lang.ClassNotFoundException: org.jenkinsci.plugins.workflow.multibranch.yaml.pipeline.PipelineAsYamlScriptFlowDefinition
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 20 more
        
     I think it's related to a certain plugin or dependency that is missing.

**Comment by oleg-nenashev** [comment]
@marounayli In version 1.0-beta-25 the Pipeline as YAML plugin is a mandatory requirement. So you will get this error if the plugin is not installed in your directory. You can update to 1.0-beta-26+ which no longer requires the plugin after https://github.com/jenkinsci/jenkinsfile-runner/pull/463

**Comment by marounayli** [comment]
Thank you so much! It works!
