### ISSUE TITLE
with 1.0-beta-19, sometimes SEVERE error occurred.

### ISSUE THREAD

**Issue by hyunil-shin** [jenkinsci/jenkinsfile-runner#528]
### Version report

Jenkins and plugins versions report:

```
1.0-beta-19
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Linux
```

### Reproduction steps

I deployed jenkinsfile-runner in kubernetes as pod.
Usually it worked very well.
Sometimes, SEVERE error occurred and pod was not worked.

```
2021-06-15 07:18:50.117+0000 [id=1]     WARNING j.branch.WorkspaceLocatorImpl#getWorkspaceRoot: JENKINS-2111 path sanitization ineffective when using legacy Workspace Root Directory ‘/build’; switch to ‘${JENKINS_HOME}/workspace/${ITEM_FULL_NAME}’ as in JENKINS-8446 / JENKINS-21942
2021-06-15 07:18:50.152+0000 [id=1]     INFO    o.c.j.p.k.KubernetesClientProvider$SaveableListenerImpl#onChange: Invalidating Kubernetes client: kubernetes null
2021-06-15 07:18:50.166+0000 [id=1]     INFO    j.m.JenkinsLocationConfiguration#preventRootUrlBeingInvalid: Invalid URL received: http://localhost:-1/jenkins/, considered as null
2021-06-15 07:18:54.610+0000 [id=1]     SEVERE  h.i.i.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler#uncaughtException: A thread (main/1) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.io.FileNotFoundException: /tmp/jenkinsfileRunner.tmp/jfr7762827885266829059.run/jobs/job/builds/1/log (No such file or directory)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at org.kohsuke.stapler.framework.io.LargeText$FileSession.<init>(LargeText.java:399)
        at org.kohsuke.stapler.framework.io.LargeText$2.open(LargeText.java:121)
        at org.kohsuke.stapler.framework.io.LargeText.writeLogTo(LargeText.java:212)
        at hudson.console.AnnotatedLargeText.writeLogTo(AnnotatedLargeText.java:165)
        at hudson.model.Run.writeWholeLogTo(Run.java:1556)
        at io.jenkins.jenkinsfile.runner.Runner.writeLogTo(Runner.java:134)
        at io.jenkins.jenkinsfile.runner.Runner.run(Runner.java:94)
Caused: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.jenkins.jenkinsfile.runner.JenkinsfileRunnerLauncher.doLaunch(JenkinsfileRunnerLauncher.java:32)
        at io.jenkins.jenkinsfile.runner.JenkinsLauncher.launch(JenkinsLauncher.java:83)
        at io.jenkins.jenkinsfile.runner.App.run(App.java:13)
        at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.run(Bootstrap.java:312)
        at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.main(Bootstrap.java:135)
```

### Results

Expected result:

 No SEVERE error.
Actual result:

**Comment by oleg-nenashev** [comment]
That's odd but looks like a real bug caused by a race condition somewhere. 

P.S: Ideally Jenkinsfile Runner should support not writing the build log to the filesystem, it is a performance overhead
