### ISSUE TITLE
"Error deleting stale/expired events from EventHistoryStore" in pipeline

### ISSUE THREAD

**Issue by fwilhe** [jenkinsci/jenkinsfile-runner#72]
Hi,

I've seen this error in a pipeline run by Jenkinsfile runner. I suspect this might be a race condition between Jenkinsfile runner deleting `/tmp/jenkinsfileRunner.tmp` and the sse-gateway-plugin deleting `/tmp/jenkinsfileRunner.tmp/jfr2051626485582005540.run/logs/sse-events`.

I'm not sure if this issue is correct in this repo, and sadly I also can't reproduce the issue. Please close the issue if it is not relevant.

Stacktrace:

```
Finished: FAILURE
 762.648 [id=39]	SEVERE	o.j.p.s.EventHistoryStore$DeleteStaleHistoryTask#run: Error deleting stale/expired events from EventHistoryStore.
java.nio.file.NoSuchFileException: /tmp/jenkinsfileRunner.tmp/jfr2051626485582005540.run/logs/sse-events
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at org.jenkinsci.plugins.ssegateway.EventHistoryStore.deleteAllFilesInDir(EventHistoryStore.java:215)
	at org.jenkinsci.plugins.ssegateway.EventHistoryStore.deleteStaleHistory(EventHistoryStore.java:192)
	at org.jenkinsci.plugins.ssegateway.EventHistoryStore$DeleteStaleHistoryTask.run(EventHistoryStore.java:268)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by fwilhe** [comment]
Nevermind, this is not jenkinsfile runner related, I mixed up build logs
